version: '3'

services:
  web:
    build: .
    command: ["gunicorn", "IntegraSoft_Front.wsgi:application", "--bind", "0.0.0.0:8001"]
    volumes:
      - ./IntegraSoft_Front:/app/IntegraSoft_Front
    ports:
      - "8001:8001"
  nginx:
    build: .
    ports:
      - "80:80"



