version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    command: ["gunicorn", "IntegraSoft_Front.wsgi:application", "--bind", "0.0.0.0:8001"]
    volumes:
      - ./IntegraSoft_Front:/app/IntegraSoft_Front
      - ./staticfiles:/app/staticfiles
    ports:
      - "8001:8001"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"



