name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run deployment script
      run: bash .github/scripts/deploy.sh
      env:
        SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
        SERVER_IP: ${{ secrets.SERVER_IP }}

